name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build and create macOS app
        run: make macapp
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/Spotify Tray.dmg
          name: "spotify-tray ${{ env.VERSION }}"
          generate_release_notes: true
