name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build/Bundle
        run: make bundle
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/Spotify Tray.dmg
          name: "spotify-tray ${{ github.ref }}"
          generate_release_notes: true
